#############################################################################
# Makefile for building: Kanren
# Generated by qmake (2.01a) (Qt 4.6.2) on: Tue Mar 16 22:19:30 2010
# Project:  Kanren.pro
# Template: app
# Command: /home/jjones/qtsdk/qt/bin/qmake -spec ../../../qtsdk/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile Kanren.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../qtsdk/qt/mkspecs/linux-g++-64 -I. -I../../../qtsdk/qt/include/QtCore -I../../../qtsdk/qt/include/QtGui -I../../../qtsdk/qt/include/QtSql -I../../../qtsdk/qt/include -I. -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/jjones/qtsdk/qt/lib
LIBS          = $(SUBLIBS)  -L/home/jjones/qtsdk/qt/lib -lQtSql -L/home/jjones/qtsdk/qt/lib -lQtGui -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/jjones/qtsdk/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		scribblearea.cpp \
		kanjilabel.cpp moc_mainwindow.cpp \
		moc_scribblearea.cpp \
		moc_kanjilabel.cpp
OBJECTS       = main.o \
		mainwindow.o \
		scribblearea.o \
		kanjilabel.o \
		moc_mainwindow.o \
		moc_scribblearea.o \
		moc_kanjilabel.o
DIST          = ../../../qtsdk/qt/mkspecs/common/g++.conf \
		../../../qtsdk/qt/mkspecs/common/unix.conf \
		../../../qtsdk/qt/mkspecs/common/linux.conf \
		../../../qtsdk/qt/mkspecs/qconfig.pri \
		../../../qtsdk/qt/mkspecs/features/qt_functions.prf \
		../../../qtsdk/qt/mkspecs/features/qt_config.prf \
		../../../qtsdk/qt/mkspecs/features/exclusive_builds.prf \
		../../../qtsdk/qt/mkspecs/features/default_pre.prf \
		../../../qtsdk/qt/mkspecs/features/debug.prf \
		../../../qtsdk/qt/mkspecs/features/default_post.prf \
		../../../qtsdk/qt/mkspecs/features/warn_on.prf \
		../../../qtsdk/qt/mkspecs/features/qt.prf \
		../../../qtsdk/qt/mkspecs/features/unix/thread.prf \
		../../../qtsdk/qt/mkspecs/features/moc.prf \
		../../../qtsdk/qt/mkspecs/features/resources.prf \
		../../../qtsdk/qt/mkspecs/features/uic.prf \
		../../../qtsdk/qt/mkspecs/features/yacc.prf \
		../../../qtsdk/qt/mkspecs/features/lex.prf \
		../../../qtsdk/qt/mkspecs/features/include_source_dir.prf \
		Kanren.pro
QMAKE_TARGET  = Kanren
DESTDIR       = 
TARGET        = Kanren

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Kanren.pro  ../../../qtsdk/qt/mkspecs/linux-g++-64/qmake.conf ../../../qtsdk/qt/mkspecs/common/g++.conf \
		../../../qtsdk/qt/mkspecs/common/unix.conf \
		../../../qtsdk/qt/mkspecs/common/linux.conf \
		../../../qtsdk/qt/mkspecs/qconfig.pri \
		../../../qtsdk/qt/mkspecs/features/qt_functions.prf \
		../../../qtsdk/qt/mkspecs/features/qt_config.prf \
		../../../qtsdk/qt/mkspecs/features/exclusive_builds.prf \
		../../../qtsdk/qt/mkspecs/features/default_pre.prf \
		../../../qtsdk/qt/mkspecs/features/debug.prf \
		../../../qtsdk/qt/mkspecs/features/default_post.prf \
		../../../qtsdk/qt/mkspecs/features/warn_on.prf \
		../../../qtsdk/qt/mkspecs/features/qt.prf \
		../../../qtsdk/qt/mkspecs/features/unix/thread.prf \
		../../../qtsdk/qt/mkspecs/features/moc.prf \
		../../../qtsdk/qt/mkspecs/features/resources.prf \
		../../../qtsdk/qt/mkspecs/features/uic.prf \
		../../../qtsdk/qt/mkspecs/features/yacc.prf \
		../../../qtsdk/qt/mkspecs/features/lex.prf \
		../../../qtsdk/qt/mkspecs/features/include_source_dir.prf \
		/home/jjones/qtsdk/qt/lib/libQtSql.prl \
		/home/jjones/qtsdk/qt/lib/libQtCore.prl \
		/home/jjones/qtsdk/qt/lib/libQtGui.prl
	$(QMAKE) -spec ../../../qtsdk/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile Kanren.pro
../../../qtsdk/qt/mkspecs/common/g++.conf:
../../../qtsdk/qt/mkspecs/common/unix.conf:
../../../qtsdk/qt/mkspecs/common/linux.conf:
../../../qtsdk/qt/mkspecs/qconfig.pri:
../../../qtsdk/qt/mkspecs/features/qt_functions.prf:
../../../qtsdk/qt/mkspecs/features/qt_config.prf:
../../../qtsdk/qt/mkspecs/features/exclusive_builds.prf:
../../../qtsdk/qt/mkspecs/features/default_pre.prf:
../../../qtsdk/qt/mkspecs/features/debug.prf:
../../../qtsdk/qt/mkspecs/features/default_post.prf:
../../../qtsdk/qt/mkspecs/features/warn_on.prf:
../../../qtsdk/qt/mkspecs/features/qt.prf:
../../../qtsdk/qt/mkspecs/features/unix/thread.prf:
../../../qtsdk/qt/mkspecs/features/moc.prf:
../../../qtsdk/qt/mkspecs/features/resources.prf:
../../../qtsdk/qt/mkspecs/features/uic.prf:
../../../qtsdk/qt/mkspecs/features/yacc.prf:
../../../qtsdk/qt/mkspecs/features/lex.prf:
../../../qtsdk/qt/mkspecs/features/include_source_dir.prf:
/home/jjones/qtsdk/qt/lib/libQtSql.prl:
/home/jjones/qtsdk/qt/lib/libQtCore.prl:
/home/jjones/qtsdk/qt/lib/libQtGui.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../../qtsdk/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile Kanren.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Kanren1.0.0 || $(MKDIR) .tmp/Kanren1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Kanren1.0.0/ && $(COPY_FILE) --parents mainwindow.h scribblearea.h kanjilabel.h .tmp/Kanren1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp scribblearea.cpp kanjilabel.cpp .tmp/Kanren1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/Kanren1.0.0/ && (cd `dirname .tmp/Kanren1.0.0` && $(TAR) Kanren1.0.0.tar Kanren1.0.0 && $(COMPRESS) Kanren1.0.0.tar) && $(MOVE) `dirname .tmp/Kanren1.0.0`/Kanren1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Kanren1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_scribblearea.cpp moc_kanjilabel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_scribblearea.cpp moc_kanjilabel.cpp
moc_mainwindow.cpp: scribblearea.h \
		mainwindow.h
	/home/jjones/qtsdk/qt/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_scribblearea.cpp: scribblearea.h
	/home/jjones/qtsdk/qt/bin/moc $(DEFINES) $(INCPATH) scribblearea.h -o moc_scribblearea.cpp

moc_kanjilabel.cpp: kanjilabel.h
	/home/jjones/qtsdk/qt/bin/moc $(DEFINES) $(INCPATH) kanjilabel.h -o moc_kanjilabel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui \
		scribblearea.h \
		kanjilabel.h
	/home/jjones/qtsdk/qt/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		scribblearea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		scribblearea.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

scribblearea.o: scribblearea.cpp scribblearea.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scribblearea.o scribblearea.cpp

kanjilabel.o: kanjilabel.cpp kanjilabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kanjilabel.o kanjilabel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_scribblearea.o: moc_scribblearea.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scribblearea.o moc_scribblearea.cpp

moc_kanjilabel.o: moc_kanjilabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_kanjilabel.o moc_kanjilabel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

